name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: true
      comment_id:
        required: true
      job:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:    
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - name: ${{github.event.inputs.id}}
        run: echo job id ${{ inputs.id }}      
      - uses: actions/checkout@v4
      - name: digger run
        uses: diggerhq/digger@v0.4.10
        with:
          setup-aws: false
          disable-locking: true
          digger-hostname: 'https://c1db-5-151-139-93.ngrok-free.app '
          digger-organisation: 'digger'
          digger-token: ${{ secrets.DIGGER_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
         
